// Copy bilingue de la landing publica (rockie.plus).
// Default: ingles. Sin menciones a ciudades ni programas geograficos.

export const LANDING_COPY = {
  en: {
    navAria: 'Sections',
    nav: { system: 'System', device: 'Device', rockie: 'Rockie', prototype: 'Prototype', teamHq: 'Team HQ' },
    hasAccount: 'Start Now',
    start: 'Get started',
    langAria: 'Language',
    langBtn: 'ES',
    langCurrent: 'EN',
    hero: {
      eyebrow: 'App available now',
      titleBefore: 'A pocket companion for the ',
      titleEm: 'goals',
      titleAfter: ' that matter.',
      sub: 'Use RockiePlus today on phone, tablet, or computer. Rockie 1, our pocket companion, is coming soon. Same account. Everything syncs.',
      ctaPrimary: 'Start free',
      ctaSecondary: 'I have an account',
      comingSoon: 'Rockie 1 · Coming soon',
    },
    chips: { goals: 'App today', made: 'Coming soon' },
    idea: {
      line: '"Most tools add noise. RockiePlus helps you move real goals and projects forward: proof, streaks, people… and soon Rockie 1."',
      punch: '',
    },
    problem: {
      eyebrow: 'The problem',
      titleBefore: 'Having a goal is ',
      titleEm: 'not',
      titleAfter: ' the same as moving it.',
      sub: 'You want life goals and real projects, and end up with lists, chats, and empty checks. What’s missing is a system that sets, proves, and grows, with you and with others.',
      bridge: 'That’s why RockiePlus: Set. Prove. Grow.',
      announce: {
        badge: 'Rockie 1 · Coming soon',
        title: 'Rockie 1 is about to shout it.',
        sub: 'The pocket companion is almost here. Join the waitlist, and send wild ideas we actually love building. Same account as the app. Everything syncs.',
      },
      cards: [
        {
          title: 'Ideas with no floor',
          body: 'The goal lives in your head or on a list. Without Area → Goal → today’s action, nothing pushes forward.',
          tag: 'No engine',
          icon: 'ti-flag-off',
          accent: 'var(--berry)',
          soft: 'var(--berry-soft)',
        },
        {
          title: 'Invisible progress',
          body: 'Saying “I’m on it” doesn’t count. Without proof, a buddy, or a team that sees it, you can lie to yourself, and the goal cools off.',
          tag: 'No proof',
          icon: 'ti-eye-off',
          accent: 'var(--amber)',
          soft: 'var(--amber-soft)',
        },
        {
          title: 'Alone in the noise',
          body: 'No challenge, streak, or people beside you, you walk alone. Organizing the day by hand is another fight; voice should sort it.',
          tag: 'No crew',
          icon: 'ti-users-minus',
          accent: 'var(--olive)',
          soft: 'var(--olive-soft)',
        },
      ],
    },
    system: {
      eyebrow: 'The system',
      title: 'Set. Prove. Grow.',
      sub: 'One flow for goals and projects, not another feature checklist.',
      footnote: 'Same account on phone, tablet, PC… and soon Rockie 1.',
      sims: {
        set: {
          listening: 'Listening',
          transcript: '"I want to run a 5K"',
          goalLabel: 'Goal',
          goal: 'Run a 5K',
          habits: ['Train', 'Stretch', 'Rest'],
          mapGoal: '5K',
          mapExtra: 'Photo',
          you: 'You',
          mapMetaA: 'Bench 100kg',
          mapMetaB: '12 books',
        },
        prove: {
          habit: 'Train 20 min',
          time: '19:00',
          tag: 'HEALTH',
          pending: 'Waiting for proof',
          swipe: 'Swipe up to validate',
          howTitle: 'How to validate?',
          howNote: 'Take a photo',
          withPhoto: 'With photo',
          withPhotoSub: '+100 XP · +25 🪙 · AI checks',
          justDid: 'I did it',
          justDidSub: '+40 XP · +10 🪙 · no photo',
          shot: 'Proof photo',
          validating: 'AI checking…',
          done: 'Validated',
          streakUp: 'Streak +1',
        },
        grow: {
          group: 'Your crew',
          together: 'Growing together',
          members: ['You', 'Ana', 'Leo'],
          days: ['12', '9', '7'],
          feed: [
            'You checked Train',
            'Ana kept the streak',
            'Leo joined the challenge',
            'Crew streak alive',
          ],
        },
      },
      steps: [
        {
          id: 'set',
          n: '1',
          tone: 'brand',
          verb: 'Set',
          title: 'Pick a goal or project',
          body: 'Start with what matters. Habits are fuel, the goal is why.',
          art: '/landing/rockies/art/metas.png?v=hq-src',
        },
        {
          id: 'prove',
          n: '2',
          tone: 'berry',
          verb: 'Prove',
          title: 'Photo + AI, or a buddy',
          body: 'Saying it is not enough. Show it happened in real life.',
          art: '/landing/rockies/art/proof-ai.png?v=hq-src',
        },
        {
          id: 'grow',
          n: '3',
          tone: 'olive',
          verb: 'Grow',
          title: 'Streak, Rockie, people',
          body: 'Keep the streak. Grow your geode. Do not walk alone.',
          art: '/landing/rockies/art/juntos-hq.png?v=hq-src',
        },
      ],
    },
    device: {
      eyebrow: 'The device',
      title: 'Rockie 1 off the feed.',
      sub: 'A single-purpose companion: talk, see your day, feel your streak, without opening Instagram "just for a second."',
      orbit: 'Drag to orbit',
      badge: 'Coming soon',
      close: 'Close',
      doneCta: 'Got it',
      demoCap: 'Rockie 1 demo, see it in action',
      features: [
        { n: '1', color: 'var(--brand)', title: 'Talk', body: '"Tell me what you got done today." Voice → task or habit. Less friction.' },
        { n: '2', color: 'var(--berry)', title: 'Today', body: 'Your day on a calm screen, goals and habits without five apps.' },
        { n: '3', color: 'var(--amber)', title: 'Rockie + streak', body: 'Emotional feedback in a physical object, not another dock icon.' },
        { n: '4', color: 'var(--olive)', title: 'Shop', body: 'An inner economy that deepens the bond while you stay consistent.' },
      ],
      waitlist: {
        openCta: 'Join the waitlist',
        title: 'Rockie 1 waitlist',
        lead: 'Be first when Rockie 1 leaves the workshop. Same account as the app, everything syncs.',
        name: 'Name',
        namePh: 'Your name',
        email: 'Email',
        emailPh: 'you@email.com',
        cta: 'Join waitlist',
        sending: 'Joining…',
        okTitle: 'You are in.',
        ok: 'You are on the Rockie 1 list. We will write when it is ready.',
        errName: 'Please enter your name.',
        errEmail: 'Please enter a valid email.',
        errDup: 'That email is already on the waitlist.',
        errOffline: 'Could not reach the server. Try again later.',
        err: 'Something went wrong. Try again.',
      },
      feedback: {
        openCta: 'Propose an idea',
        title: 'We are listening.',
        lead: 'Got an idea for Rockie 1? We read every note, and we happily build the ones that stick.',
        name: 'Name (optional)',
        namePh: 'Your name',
        email: 'Email (optional)',
        emailPh: 'you@email.com',
        message: 'Your proposal',
        messagePh: 'What should Rockie 1 do, feel, or never become?',
        cta: 'Send idea',
        sending: 'Sending…',
        okTitle: 'Heard.',
        ok: 'Your idea landed in the Rockie 1 workshop. Thank you for shaping it with us.',
        errMessage: 'Write a short proposal first.',
        errEmail: 'Please enter a valid email.',
        errOffline: 'Could not reach the server. Try again later.',
        err: 'Something went wrong. Try again.',
      },
    },
    rockie: {
      eyebrow: 'Meet Rockie',
      title: 'A geode, not a drill sergeant.',
      sub: 'Rockie grows with you. Consistency cracks the stone and reveals the crystal you already had inside.',
      moods: [
        { src: '/landing/rockies/moods/amigable.png', title: 'Friendly', sub: 'Warm presence' },
        { src: '/landing/rockies/moods/curioso.png', title: 'Curious', sub: 'Asks what matters' },
        { src: '/landing/rockies/moods/divertido.png', title: 'Playful', sub: 'No toxicity' },
        { src: '/landing/rockies/moods/motivador.png', title: 'Motivating', sub: 'Pushes with care' },
        { src: '/landing/rockies/moods/adaptable.png', title: 'Adaptive', sub: 'At your pace' },
      ],
      geoda: 'Habits do not fix you: they reveal you. Rockie is the crystal that appears when you stop lying to yourself and stop walking alone.',
    },
    link: {
      eyebrow: 'How it links',
      title: 'One system of truth.',
      sub: 'Talk on the device. Prove it in the app. Move forward with your team in HQ.',
      nodes: [
        { t: 'Rockie 1', d: 'Voice · Today · streak · ritual off the phone' },
        { t: 'RockiePlus app', d: 'Goals · photo + AI · community · XP' },
        { t: 'Team HQ', d: 'Board · milestones · done = proven' },
      ],
    },
    prototype: {
      eyebrow: 'Built, not rendered',
      title: 'Real electronics. Real workshop.',
      sub: 'Screen, battery, mic, firmware, 3D shell, running as a living prototype. Hardware you can hold, not a slide deck.',
      shots: [
        ['/landing/proto/proto-carcasa.png', 'Shell · pocket form factor'],
        ['/landing/proto/proto-stack-interno.png', 'Internal stack · board, battery, mic, display'],
        ['/landing/proto/proto-ui-hablar.png', 'UI · Talk'],
        ['/landing/proto/proto-ui-racha.png', 'UI · Streak / Today / Rockie / Shop'],
      ],
      videoCap: 'Prototype demo · live firmware + UI',
    },
    specs: {
      eyebrow: 'Specs',
      title: 'What is inside today.',
      sub: 'Lab prototype specs, the leap to production hardware is the next chapter.',
      blocks: [
        { h: 'Display & body', items: [['Touch display', 'living UI'], ['3D shell', 'pocket'], ['Single purpose', '']] },
        { h: 'Input', items: [['Microphone', 'voice'], ['Talk / Today / Rockie / Shop', ''], ['Local-first', 'mode']] },
        { h: 'Power & board', items: [['Onboard battery', ''], ['Custom firmware', ''], ['Cloud sync', 'in progress']] },
        { h: 'Software', items: [['RockiePlus app', 'goals + AI'], ['Team HQ', 'projects'], ['One ecosystem', '']] },
      ],
    },
    teamHqTeaser: {
      eyebrow: 'Team HQ',
      titleBefore: 'When the goal is shared, you need a ',
      titleEm: 'real HQ',
      titleAfter: '.',
      sub: 'Manifesto, board, proof, and milestones, for crews that move projects together.',
      cta: 'Discover Team HQ',
    },
    teamHq: {
      back: 'RockiePlus',
      hasAccount: 'Start Now',
      start: 'Get started',
      hero: {
        eyebrow: 'Team HQ',
        titleBefore: 'The HQ where your crew turns a goal into ',
        titleEm: 'board, proof, and streak',
        titleAfter: '.',
        sub: 'Not another chat full of “I’ll do it.” A shared space for projects with more detail, for organizations, clubs, group work, companies, and personal projects with friends.',
        ctaPrimary: 'Open the app',
        ctaSecondary: 'I have an account',
      },
      forWhom: {
        eyebrow: 'Who it is for',
        title: 'Same HQ. Different crews.',
        sub: 'If more than one person owns the outcome, Team HQ fits.',
        cards: [
          {
            title: 'Organizations',
            body: 'One north star, clear roles, and a board that does not live in seven chats.',
            art: '/landing/rockies/art/rockie-terno-1.png',
          },
          {
            title: 'Clubs & communities',
            body: 'Events, shifts, and shared wins, with proof that things actually happened.',
            art: '/landing/rockies/art/rockie-hq-hat.png',
          },
          {
            title: 'Group work',
            body: 'Thesis, hackathons, study crews: tasks with owners and validation, not ghosting.',
            art: '/landing/rockies/art/rockie-hq-cards.png',
          },
          {
            title: 'Companies & startups',
            body: 'Weekly fronts, milestones, and a manifesto the team can actually open.',
            art: '/landing/rockies/art/rockie-terno-3.png',
          },
          {
            title: 'Projects with friends',
            body: 'Side hustles and personal missions, serious enough to track, warm enough to stay.',
            art: '/landing/rockies/art/juntos-hq.png',
          },
        ],
      },
      pillars: {
        eyebrow: 'Inside Team HQ',
        title: 'Four rooms. One crew.',
        sub: 'Inside the app this is the Cuartel: the same product, named for how it feels to run a team.',
        items: [
          {
            title: 'Manifesto',
            body: 'Why you exist together, rules, north star, and the page the team lands on.',
            icon: 'ti-flag',
            art: '/landing/rockies/art/rockie-terno-2.png',
          },
          {
            title: 'Board',
            body: 'Columns, owners, deadlines. Work moves in public, no buried DMs.',
            icon: 'ti-layout-kanban',
            art: '/landing/rockies/art/proyectos.png',
          },
          {
            title: 'Proof',
            body: 'Validate what got done. Saying “done” is cheap; showing it keeps the streak honest.',
            icon: 'ti-camera-check',
            art: '/landing/rockies/art/rockie-terno-4.png',
          },
          {
            title: 'Milestones & crew',
            body: 'XP, streaks, and the people who show up, progress you can feel as a group.',
            icon: 'ti-trophy',
            art: '/landing/rockies/art/metas.png',
          },
        ],
      },
      close: {
        eyebrow: 'Ready',
        title: 'Put the crew in one HQ.',
        sub: 'Start in RockiePlus, Team HQ (Cuartel) lives inside the same account.',
        ctaPrimary: 'Get started',
        ctaSecondary: 'Back to RockiePlus',
      },
    },
    team: {
      eyebrow: 'Who builds it',
      title: 'A team with soul.',
      sub: 'Friends who rebuild together. A humble workshop. Everything we have, poured into App, Rockie 1, and HQ.',
      alvaro: {
        name: 'Álvaro Zúñiga',
        role: 'Founder · Firmware & device',
        body: 'Leads Rockie 1 and the firmware. Product vision and the idea of healing attention.',
      },
      jose: {
        name: 'José Quispe',
        role: 'Co-founder · Code & app',
        body: 'Leads RockiePlus software: goals, proof, experience. The code that brings the ecosystem to life.',
      },
      strip: 'Humble workshop. Enough tools. Maximum heart. Friends who show up with ideas.',
    },
    cta: {
      eyebrow: 'What is next',
      title: 'From working prototype to a companion ready to ship.',
      sub: 'We are taking Rockie 1 from a living build to a physical AI companion, with goals, proof, and a team that builds with soul.',
      tryApp: 'Try the app',
      writeUs: 'Write to us',
    },
    footer: {
      tagline: 'Turn habits into real-life wins together · Rockie 1',
      legal: 'Privacy & terms',
    },
  },

  es: {
    navAria: 'Secciones',
    nav: { system: 'Sistema', device: 'Aparato', rockie: 'Rockie', prototype: 'Prototipo', teamHq: 'Team HQ' },
    hasAccount: 'Ya tengo cuenta',
    start: 'Empieza',
    langAria: 'Idioma',
    langBtn: 'EN',
    langCurrent: 'ES',
    hero: {
      eyebrow: 'App disponible ahora',
      titleBefore: 'Un compañero de bolsillo para las ',
      titleEm: 'metas',
      titleAfter: ' que importan.',
      sub: 'Usa RockiePlus hoy en celular, tablet o computadora. Rockie 1, nuestro compañero de bolsillo, llega pronto. Misma cuenta. Todo se sincroniza.',
      ctaPrimary: 'Empieza gratis',
      ctaSecondary: 'Ya tengo cuenta',
      comingSoon: 'Rockie 1 · Coming soon',
    },
    chips: { goals: 'App hoy', made: 'Coming soon' },
    idea: {
      line: '"La mayoría de herramientas suman ruido. RockiePlus te ayuda a avanzar metas y proyectos reales: prueba, rachas, gente… y pronto Rockie 1."',
      punch: '',
    },
    problem: {
      eyebrow: 'El problema',
      titleBefore: 'Tener una meta ',
      titleEm: 'no',
      titleAfter: ' es avanzarla.',
      sub: 'Quieres metas de vida y de proyecto, y acabas con listas, chats y checks sin prueba. Falta un sistema que defina, demuestre y crezca contigo y con otros.',
      bridge: 'Por eso RockiePlus: Define. Demuestra. Crece.',
      announce: {
        badge: 'Rockie 1 · Coming soon',
        title: 'Rockie 1 ya viene a gritarlo.',
        sub: 'El compañero de bolsillo casi llega. Súmate a la lista, y mándanos ideas locas que con gusto construiremos. Misma cuenta que la app. Todo se sincroniza.',
      },
      cards: [
        {
          title: 'Ideas sin piso',
          body: 'La meta vive en la cabeza o en una lista. Sin Área → Meta → acción del día, no hay motor que empuje.',
          tag: 'Sin motor',
          icon: 'ti-flag-off',
          accent: 'var(--berry)',
          soft: 'var(--berry-soft)',
        },
        {
          title: 'Avance invisible',
          body: 'Decir «voy» no cuenta. Sin prueba, buddy o equipo que lo vea, te puedes mentir, y la meta se enfría.',
          tag: 'Sin prueba',
          icon: 'ti-eye-off',
          accent: 'var(--amber)',
          soft: 'var(--amber-soft)',
        },
        {
          title: 'Solo en el ruido',
          body: 'Sin reto, racha o gente a tu lado, caminas solo. Organizar el día a mano es otra pelea, la voz debería ordenarlo.',
          tag: 'Sin gente',
          icon: 'ti-users-minus',
          accent: 'var(--olive)',
          soft: 'var(--olive-soft)',
        },
      ],
    },
    system: {
      eyebrow: 'El sistema',
      title: 'Define. Demuestra. Crece.',
      sub: 'Un flujo para metas y proyectos, no otra lista de features.',
      footnote: 'Misma cuenta en celular, tablet, PC… y pronto Rockie 1.',
      sims: {
        set: {
          listening: 'Escuchando',
          transcript: '"Quiero correr un 5K"',
          goalLabel: 'Meta',
          goal: 'Correr un 5K',
          habits: ['Entrenar', 'Estirar', 'Descanso'],
          mapGoal: '5K',
          mapExtra: 'Foto',
          you: 'Tú',
          mapMetaA: 'Press 100kg',
          mapMetaB: '12 libros',
        },
        prove: {
          habit: 'Entrenar 20 min',
          time: '19:00',
          tag: 'SALUD',
          pending: 'Esperando prueba',
          swipe: 'Desliza arriba para validar',
          howTitle: '¿Cómo validar?',
          howNote: 'Toma una foto',
          withPhoto: 'Con foto',
          withPhotoSub: '+100 XP · +25 🪙 · verifica IA',
          justDid: 'Lo hice',
          justDidSub: '+40 XP · +10 🪙 · sin foto',
          shot: 'Foto prueba',
          validating: 'IA revisando…',
          done: 'Validado',
          streakUp: 'Racha +1',
        },
        grow: {
          group: 'Tu crew',
          together: 'Creciendo juntos',
          members: ['Tú', 'Ana', 'Leo'],
          days: ['12', '9', '7'],
          feed: [
            'Validaste Entrenar',
            'Ana mantuvo la racha',
            'Leo se unió al reto',
            'Racha del crew viva',
          ],
        },
      },
      steps: [
        {
          id: 'set',
          n: '1',
          tone: 'brand',
          verb: 'Define',
          title: 'Elige una meta o proyecto',
          body: 'Empieza por lo que importa. Los hábitos son combustible, la meta es el porqué.',
          art: '/landing/rockies/art/metas.png?v=hq-src',
        },
        {
          id: 'prove',
          n: '2',
          tone: 'berry',
          verb: 'Demuestra',
          title: 'Foto + IA, o un buddy',
          body: 'Decir no basta. Demuestra qué pasó en la vida real.',
          art: '/landing/rockies/art/proof-ai.png?v=hq-src',
        },
        {
          id: 'grow',
          n: '3',
          tone: 'olive',
          verb: 'Crece',
          title: 'Racha, Rockie, gente',
          body: 'Mantén la racha. Crece tu geoda. No camines solo.',
          art: '/landing/rockies/art/juntos-hq.png?v=hq-src',
        },
      ],
    },
    device: {
      eyebrow: 'El aparato',
      title: 'Rockie 1 fuera del feed.',
      sub: 'Compañero de un solo propósito: habla, ve tu día, siente tu racha, sin abrir Instagram "de paso".',
      orbit: 'Arrastra para orbitar',
      badge: 'Coming soon',
      close: 'Cerrar',
      doneCta: 'Listo',
      demoCap: 'Demo de Rockie 1, míralo en acción',
      features: [
        { n: '1', color: 'var(--brand)', title: 'Hablar', body: '"Cuéntame qué lograste hoy." Voz → tarea o hábito. Menos fricción.' },
        { n: '2', color: 'var(--berry)', title: 'Hoy', body: 'Tu día en una pantalla calmada, metas y hábitos sin cinco apps.' },
        { n: '3', color: 'var(--amber)', title: 'Rockie + racha', body: 'Feedback emocional en un objeto físico, no otro icono del dock.' },
        { n: '4', color: 'var(--olive)', title: 'Tienda', body: 'Economía interna que profundiza el vínculo mientras eres constante.' },
      ],
      waitlist: {
        openCta: 'Unirme a la lista',
        title: 'Lista de Rockie 1',
        lead: 'Sé el primero cuando Rockie 1 salga del taller. Misma cuenta que la app, todo se sincroniza.',
        name: 'Nombre',
        namePh: 'Tu nombre',
        email: 'Correo',
        emailPh: 'tu@email.com',
        cta: 'Unirme a la lista',
        sending: 'Uniendo…',
        okTitle: 'Ya estás dentro.',
        ok: 'Ya estás en la lista de Rockie 1. Te escribimos cuando esté listo.',
        errName: 'Escribe tu nombre.',
        errEmail: 'Escribe un correo válido.',
        errDup: 'Ese correo ya está en la lista.',
        errOffline: 'No pudimos conectar. Intenta más tarde.',
        err: 'Algo salió mal. Intenta de nuevo.',
      },
      feedback: {
        openCta: 'Proponer una idea',
        title: 'Estamos escuchando.',
        lead: '¿Una idea para Rockie 1? Leemos cada nota, y con gusto construimos las que pegan.',
        name: 'Nombre (opcional)',
        namePh: 'Tu nombre',
        email: 'Correo (opcional)',
        emailPh: 'tu@email.com',
        message: 'Tu propuesta',
        messagePh: '¿Qué debería hacer, sentir o nunca ser Rockie 1?',
        cta: 'Enviar idea',
        sending: 'Enviando…',
        okTitle: 'Escuchado.',
        ok: 'Tu idea llegó al taller de Rockie 1. Gracias por darle forma con nosotros.',
        errMessage: 'Escribe una propuesta primero.',
        errEmail: 'Escribe un correo válido.',
        errOffline: 'No pudimos conectar. Intenta más tarde.',
        err: 'Algo salió mal. Intenta de nuevo.',
      },
    },
    rockie: {
      eyebrow: 'Conoce a Rockie',
      title: 'Una geoda, no un capataz.',
      sub: 'Rockie crece contigo. La constancia agrieta la piedra y revela el cristal que ya tenías dentro.',
      moods: [
        { src: '/landing/rockies/moods/amigable.png', title: 'Amigable', sub: 'Presencia cálida' },
        { src: '/landing/rockies/moods/curioso.png', title: 'Curioso', sub: 'Pregunta qué importa' },
        { src: '/landing/rockies/moods/divertido.png', title: 'Divertido', sub: 'Sin toxicidad' },
        { src: '/landing/rockies/moods/motivador.png', title: 'Motivador', sub: 'Empuja con cuidado' },
        { src: '/landing/rockies/moods/adaptable.png', title: 'Adaptable', sub: 'A tu ritmo' },
      ],
      geoda: 'Los hábitos no te arreglan: te revelan. Rockie es el cristal que aparece cuando dejas de autoengañarte y de caminar solo.',
    },
    link: {
      eyebrow: 'Cómo se vincula',
      title: 'Un solo sistema de verdad.',
      sub: 'Habla en el aparato. Demuestra en la app. Avanza con tu equipo en el HQ.',
      nodes: [
        { t: 'Rockie 1', d: 'Voz · Hoy · racha · ritual fuera del teléfono' },
        { t: 'App RockiePlus', d: 'Metas · foto + IA · comunidad · XP' },
        { t: 'Team HQ', d: 'Tablero · hitos · hecho = demostrado' },
      ],
    },
    prototype: {
      eyebrow: 'Hecho, no renderizado',
      title: 'Electrónica real. Taller real.',
      sub: 'Pantalla, batería, micro, firmware, carcasa 3D, un prototipo vivo. Hardware que puedes tocar, no una diapositiva.',
      shots: [
        ['/landing/proto/proto-carcasa.png', 'Carcasa · factor de bolsillo'],
        ['/landing/proto/proto-stack-interno.png', 'Stack interno · placa, batería, micro, pantalla'],
        ['/landing/proto/proto-ui-hablar.png', 'UI · Hablar'],
        ['/landing/proto/proto-ui-racha.png', 'UI · Racha / Hoy / Rockie / Tienda'],
      ],
      videoCap: 'Demo del prototipo · firmware + UI vivos',
    },
    specs: {
      eyebrow: 'Specs',
      title: 'Qué hay hoy dentro.',
      sub: 'Specs de prototipo de laboratorio, el salto a producción es el siguiente capítulo.',
      blocks: [
        { h: 'Pantalla y cuerpo', items: [['Pantalla táctil', 'UI viva'], ['Carcasa 3D', 'bolsillo'], ['Un solo propósito', '']] },
        { h: 'Entrada', items: [['Micrófono', 'voz'], ['Hablar / Hoy / Rockie / Tienda', ''], ['Modo local', 'primero']] },
        { h: 'Energía y placa', items: [['Batería', 'a bordo'], ['Firmware propio', ''], ['Sync nube', 'en progreso']] },
        { h: 'Software', items: [['App RockiePlus', 'metas + IA'], ['Team HQ', 'proyectos'], ['Un ecosistema', '']] },
      ],
    },
    teamHqTeaser: {
      eyebrow: 'Team HQ',
      titleBefore: 'Cuando la meta es compartida, hace falta un ',
      titleEm: 'cuartel de verdad',
      titleAfter: '.',
      sub: 'Manifiesto, tablero, prueba e hitos, para equipos que mueven proyectos juntos.',
      cta: 'Conocer Team HQ',
    },
    teamHq: {
      back: 'RockiePlus',
      hasAccount: 'Ya tengo cuenta',
      start: 'Empieza',
      hero: {
        eyebrow: 'Team HQ',
        titleBefore: 'El cuartel donde tu equipo baja la meta a ',
        titleEm: 'tablero, prueba y racha',
        titleAfter: '.',
        sub: 'No es otro chat lleno de «ya lo hago». Es un espacio compartido para organizar proyectos con más detalle, organizaciones, clubes, trabajos en grupo, empresas y proyectos personales con amigos.',
        ctaPrimary: 'Abrir la app',
        ctaSecondary: 'Ya tengo cuenta',
      },
      forWhom: {
        eyebrow: 'Para quién',
        title: 'El mismo HQ. Distintos equipos.',
        sub: 'Si más de una persona responde por el resultado, Team HQ encaja.',
        cards: [
          {
            title: 'Organizaciones',
            body: 'Una estrella del norte, roles claros y un tablero que no vive en siete chats.',
            art: '/landing/rockies/art/rockie-terno-1.png',
          },
          {
            title: 'Clubes y comunidades',
            body: 'Eventos, turnos y victorias compartidas, con prueba de que sí pasó.',
            art: '/landing/rockies/art/rockie-hq-hat.png',
          },
          {
            title: 'Trabajos en grupo',
            body: 'Tesis, hackathons, estudio: tareas con dueño y validación, no fantasmas.',
            art: '/landing/rockies/art/rockie-hq-cards.png',
          },
          {
            title: 'Empresas y startups',
            body: 'Frentes de la semana, hitos y un manifiesto que el equipo sí abre.',
            art: '/landing/rockies/art/rockie-terno-3.png',
          },
          {
            title: 'Proyectos con amigos',
            body: 'Side projects y misiones personales, serios para rastrear, cálidos para quedarse.',
            art: '/landing/rockies/art/juntos-hq.png',
          },
        ],
      },
      pillars: {
        eyebrow: 'Qué hay dentro',
        title: 'Cuatro salas. Un equipo.',
        sub: 'En la app es el Cuartel: el mismo producto, con el nombre de cómo se siente dirigir un equipo.',
        items: [
          {
            title: 'Manifiesto',
            body: 'Por qué existen juntos, reglas, norte y la página donde aterriza el equipo.',
            icon: 'ti-flag',
            art: '/landing/rockies/art/rockie-terno-2.png',
          },
          {
            title: 'Tablero',
            body: 'Columnas, dueños, plazos. El trabajo se mueve a la vista, sin DMs enterrados.',
            icon: 'ti-layout-kanban',
            art: '/landing/rockies/art/proyectos.png',
          },
          {
            title: 'Prueba',
            body: 'Validar lo hecho. Decir «listo» es barato; demostrarlo mantiene la racha honesta.',
            icon: 'ti-camera-check',
            art: '/landing/rockies/art/rockie-terno-4.png',
          },
          {
            title: 'Hitos y equipo',
            body: 'XP, rachas y la gente que aparece, progreso que se siente en grupo.',
            icon: 'ti-trophy',
            art: '/landing/rockies/art/metas.png',
          },
        ],
      },
      close: {
        eyebrow: 'Listo',
        title: 'Pon al equipo en un solo HQ.',
        sub: 'Entra a RockiePlus, Team HQ (Cuartel) vive en la misma cuenta.',
        ctaPrimary: 'Empieza',
        ctaSecondary: 'Volver a RockiePlus',
      },
    },
    team: {
      eyebrow: 'Quién lo hace',
      title: 'Un equipo con alma.',
      sub: 'Amigos que reconstruyen juntos. Un taller humilde. Todo lo que tenemos, en la App, Rockie 1 y el HQ.',
      alvaro: {
        name: 'Álvaro Zúñiga',
        role: 'Fundador · Firmware y aparato',
        body: 'Lidera Rockie 1 y el firmware. Visión de producto y la idea de sanar la atención.',
      },
      jose: {
        name: 'José Quispe',
        role: 'Cofundador · Código y app',
        body: 'Lidera el software de RockiePlus: metas, prueba, experiencia. El código que hace vivo el ecosistema.',
      },
      strip: 'Taller humilde. Herramientas suficientes. Máximo corazón. Amigos que llegan con ideas.',
    },
    cta: {
      eyebrow: 'Lo que sigue',
      title: 'De prototipo funcional a compañero listo para fabricar.',
      sub: 'Llevamos Rockie 1 de un build vivo a un compañero de IA física, con metas, prueba y un equipo que construye con alma.',
      tryApp: 'Probar la app',
      writeUs: 'Escríbenos',
    },
    footer: {
      tagline: 'Convierte hábitos en victorias reales juntos · Rockie 1',
      legal: 'Privacidad y términos',
    },
  },
}

export const LANG_KEY = 'bplus.landing.lang'
